version: "3.9"

services:
  app:
    image: "${ECR_REPO_URL}:latest"
    container_name: mediplus
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always

  proxy:
    image: nginx:latest
    container_name: mediplus-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: always
